#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Aug 16 10:09:45 2024

@author: Estudiante
"""

# Ejercicio, programa que decida si una palabra de longitud 5 es palindromo.

def palindromo (a):
    return a == a[::-1]
    